# Generated by Django 5.2.1 on 2025-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_daily_executions',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
