# Generated by Django 5.2.1 on 2025-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_category_max_daily_executions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='executions_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
