# Generated by Django 5.2.1 on 2025-06-14 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_activity_priority_category_executions_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('activity', 'scheduled_date')},
        ),
    ]
