# Generated by Django 5.2.1 on 2025-06-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_schedule_start_time_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='schedule',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='pomodoro.schedule'),
            preserve_default=False,
        ),
    ]
