# Generated by Django 5.2.3 on 2026-03-19 22:26

import django.db.models.deletion
import pomodoro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0007_group_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=pomodoro.models.get_default_group_id, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='pomodoro.group'),
        ),
    ]
