# Generated by Django 5.2.3 on 2026-03-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0008_alter_category_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_daily_executions',
        ),
    ]
