# Generated by Django 5.2.3 on 2026-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0009_remove_group_max_daily_executions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-premium', 'name'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='premium_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='premium_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
