# Generated by Django 5.2.3 on 2026-07-07 22:55

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from datetime import datetime, timedelta


def backfill_schedule_execution_fields(apps, schema_editor):
    Schedule = apps.get_model('pomodoro', 'Schedule')
    for schedule in Schedule.objects.all().iterator():
        if schedule.start_time:
            naive_start = datetime.combine(schedule.scheduled_date, schedule.start_time)
            starts_at = timezone.make_aware(naive_start, timezone.get_current_timezone())
            schedule.requested_at = schedule.requested_at or starts_at
            schedule.starts_at = schedule.starts_at or starts_at
            schedule.expected_end_at = schedule.expected_end_at or (starts_at + timedelta(minutes=schedule.activity.duration))
        if schedule.completed and schedule.end_time:
            naive_end = datetime.combine(schedule.scheduled_date, schedule.end_time)
            schedule.completed_at = schedule.completed_at or timezone.make_aware(
                naive_end,
                timezone.get_current_timezone(),
            )
            schedule.state = 'completed'
        else:
            schedule.state = schedule.state or 'running'
        schedule.save(
            update_fields=[
                'requested_at',
                'starts_at',
                'expected_end_at',
                'completed_at',
                'state',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0010_alter_activity_options_activity_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='expected_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='scope_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='schedule',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='running', max_length=16),
        ),
        migrations.AddField(
            model_name='schedule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ActivityQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('skipped_review', 'Skipped review')], default='normal', max_length=24)),
                ('pool_number', models.PositiveIntegerField(default=1)),
                ('pool_size', models.PositiveIntegerField(default=0)),
                ('consumed_count', models.PositiveIntegerField(default=0)),
                ('skip_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_queues', to='pomodoro.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('presented', 'Presented'), ('started', 'Started'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_items', to='pomodoro.activity')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pomodoro.activityqueue')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPreferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('favorite_completed', 'Favorite completed'), ('skipped', 'Skipped'), ('skipped_completed', 'Skipped completed')], max_length=32)),
                ('weight_delta', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_events', to='pomodoro.activity')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_events', to='pomodoro.activityqueue')),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_events', to='pomodoro.activityqueueitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='queue_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='pomodoro.activityqueueitem'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['preparing', 'running']), models.Q(('scope_key', ''), _negated=True)), fields=('scope_key',), name='unique_open_schedule_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='activityqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('scope_key',), name='unique_active_queue_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='activityqueueitem',
            constraint=models.UniqueConstraint(fields=('queue', 'position'), name='unique_queue_item_position'),
        ),
        migrations.RunPython(backfill_schedule_execution_fields, migrations.RunPython.noop),
    ]
