# Generated by Django 5.2.3 on 2026-07-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0012_default_category_contract'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
