# Generated by Django 5.2.3 on 2026-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0014_group_scoped_persistent_queues'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('external_source', 'external_id'), name='unique_activity_external_identity'),
        ),
    ]
