# Generated by Django 5.2.3 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0015_activity_external_id_activity_external_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='recreated_from',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recreated_queue',
                to='pomodoro.activityqueue',
            ),
        ),
    ]
