# Generated by Django 5.2.3 on 2026-09-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0016_activityqueue_recreated_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='goal_category_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='goal_group_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_schedule_id', models.PositiveBigIntegerField(unique=True)),
                ('scope_key', models.CharField(max_length=64)),
                ('category_id_snapshot', models.PositiveBigIntegerField()),
                ('group_id_snapshot', models.PositiveBigIntegerField()),
                ('completed_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('context_source', models.CharField(choices=[('execution_start', 'Início da execução'), ('legacy_current', 'Contexto atual do legado')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_key', 'completed_at'], name='goal_fact_scope_time_idx'), models.Index(fields=['scope_key', 'group_id_snapshot', 'completed_at'], name='goal_fact_group_time_idx'), models.Index(fields=['scope_key', 'category_id_snapshot', 'completed_at'], name='goal_fact_category_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('metric', models.CharField(choices=[('minutes', 'Minutos'), ('sessions', 'Sessões')], max_length=8)),
                ('is_all_groups', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pomodoro.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pomodoro.group')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoalRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_week', models.DateField()),
                ('target', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pomodoro.weeklygoal')),
            ],
            options={
                'ordering': ['effective_week', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('group__isnull', False)), models.Q(('category__isnull', False), ('group__isnull', True)), _connector='OR'), name='goal_exactly_one_destination'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.CheckConstraint(condition=models.Q(('is_all_groups', False), ('group__isnull', False), _connector='OR'), name='goal_all_requires_group'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.CheckConstraint(condition=models.Q(('metric__in', ['minutes', 'sessions'])), name='goal_valid_metric'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='goal_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('scope_key', 'metric', 'group'), name='goal_unique_group_metric'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('scope_key', 'metric', 'category'), name='goal_unique_category_metric'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoalrevision',
            constraint=models.UniqueConstraint(fields=('goal', 'effective_week'), name='goal_unique_revision_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('target__gte', 1)), name='goal_positive_target'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('effective_week__week_day', 2)), name='goal_revision_monday'),
        ),
    ]
