# Generated by Django 5.2.3 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0017_weekly_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalActivitySkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_queue_item_id', models.PositiveBigIntegerField(unique=True)),
                ('source_queue_id', models.PositiveBigIntegerField()),
                ('scope_key', models.CharField(max_length=64)),
                ('activity_id_snapshot', models.PositiveBigIntegerField()),
                ('activity_name_snapshot', models.CharField(max_length=100)),
                ('category_id_snapshot', models.PositiveBigIntegerField()),
                ('category_name_snapshot', models.CharField(max_length=50)),
                ('category_color_snapshot', models.CharField(max_length=7)),
                ('group_id_snapshot', models.PositiveBigIntegerField()),
                ('group_name_snapshot', models.CharField(max_length=50)),
                ('group_color_snapshot', models.CharField(max_length=7)),
                ('queue_mode_snapshot', models.CharField(max_length=24)),
                ('skipped_at', models.DateTimeField()),
                ('context_source', models.CharField(choices=[('live_skip', 'Pulo confirmado'), ('legacy_current', 'Contexto atual do legado')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['scope_key', 'skipped_at'], name='goal_skip_scope_time_idx'),
                    models.Index(fields=['scope_key', 'group_id_snapshot', 'skipped_at'], name='goal_skip_group_time_idx'),
                    models.Index(fields=['scope_key', 'category_id_snapshot', 'skipped_at'], name='goal_skip_category_time_idx'),
                ],
            },
        ),
    ]
