# Generated by Django 5.2.3 on 2026-09-16 21:27

import django.db.models.deletion
from django.db import migrations, models


def classify_existing_schedules(apps, schema_editor):
    Schedule = apps.get_model('pomodoro', 'Schedule')
    Schedule.objects.filter(queue_item__isnull=True).update(execution_origin='legacy')
    Schedule.objects.filter(queue_item__isnull=False).update(execution_origin='queue')


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0018_goalactivityskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcompletion',
            name='activity_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='activity_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='execution_origin',
            field=models.CharField(choices=[('queue', 'Queue'), ('premium_direct', 'Premium direct'), ('legacy', 'Legacy')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='goalcompletion',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='continued_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuation', to='pomodoro.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='execution_origin',
            field=models.CharField(choices=[('queue', 'Queue'), ('premium_direct', 'Premium direct'), ('legacy', 'Legacy')], db_index=True, default='queue', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='planned_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='return_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_schedules', to='pomodoro.group'),
        ),
        migrations.CreateModel(
            name='GameplayTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64, unique=True)),
                ('daily_reference_minutes', models.PositiveIntegerField(default=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='gameplay_settings', to='pomodoro.group')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paid', 'Pago'), ('focus', 'Foco')], max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('ended_early_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='native', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_periods', to='pomodoro.activity')),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='premium_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='pomodoro.premiumperiod'),
        ),
        migrations.CreateModel(
            name='ExecutionIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('schedule_id_tombstone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='pomodoro.schedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'request_id'), name='execution_request_scope_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='premiumperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='premium_period_valid_dates'),
        ),
        migrations.RunPython(classify_existing_schedules, migrations.RunPython.noop),
    ]
