# Generated by Django 5.2.3 on 2026-09-25 02:16

import django.db.models.deletion
from django.db import migrations, models


def ensure_retrogames_group(apps, schema_editor):
    Group = apps.get_model('pomodoro', 'Group')
    group, _ = Group.objects.get_or_create(
        name='Retrogames',
        defaults={
            'description': 'Catálogo editorial de jogos retrô.',
            'color': '#6C5CE7',
        },
    )
    if not group.is_retro_catalog:
        group.is_retro_catalog = True
        group.save(update_fields=['is_retro_catalog'])


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0019_goalcompletion_activity_id_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('essential', 'Essencial'), ('complementary', 'Complementar')], max_length=16)),
                ('estimated_main_minutes', models.PositiveIntegerField()),
                ('play_goal', models.CharField(blank=True, default='', max_length=240)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform__generation__retro_sort_order', 'platform__sort_order', 'sort_order', 'release_year', 'activity__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RetroGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('skipped', 'Pulado')], max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetroPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['generation__retro_sort_order', 'sort_order', 'release_year', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='retro_sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_retro_catalog',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(ensure_retrogames_group, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='goalcompletion',
            name='execution_origin',
            field=models.CharField(choices=[('queue', 'Queue'), ('premium_direct', 'Premium direct'), ('retro_direct', 'Retro direct'), ('legacy', 'Legacy')], default='legacy', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='execution_origin',
            field=models.CharField(choices=[('queue', 'Queue'), ('premium_direct', 'Premium direct'), ('retro_direct', 'Retro direct'), ('legacy', 'Legacy')], db_index=True, default='queue', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_retro_catalog', True)), fields=('is_retro_catalog',), name='unique_retro_catalog_group'),
        ),
        migrations.AddField(
            model_name='retrogame',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retro_game', to='pomodoro.activity'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='retro_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='pomodoro.retrogame'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('execution_origin', 'retro_direct'), ('premium_period__isnull', True), ('queue_item__isnull', True), ('retro_game__isnull', False)), models.Q(models.Q(('execution_origin', 'retro_direct'), _negated=True), ('retro_game__isnull', True)), _connector='OR'), name='schedule_retro_origin_context'),
        ),
        migrations.AddField(
            model_name='retrogameprogress',
            name='retro_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='pomodoro.retrogame'),
        ),
        migrations.AddField(
            model_name='retroplatform',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retro_platforms', to='pomodoro.category'),
        ),
        migrations.AddField(
            model_name='retrogame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='pomodoro.retroplatform'),
        ),
        migrations.AddConstraint(
            model_name='retrogameprogress',
            constraint=models.UniqueConstraint(fields=('scope_key', 'retro_game'), name='retro_progress_scope_game_unique'),
        ),
        migrations.AddConstraint(
            model_name='retrogameprogress',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='retro_progress_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='retrogameprogress',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed', 'skipped'])), name='retro_progress_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='retrogameprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='retro_progress_completion_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='retroplatform',
            constraint=models.UniqueConstraint(fields=('generation', 'name'), name='retro_platform_generation_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='retroplatform',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 1)), name='retro_platform_positive_order'),
        ),
        migrations.AddConstraint(
            model_name='retroplatform',
            constraint=models.CheckConstraint(condition=models.Q(('release_year__isnull', True), ('release_year__range', (1970, 2100)), _connector='OR'), name='retro_platform_valid_release_year'),
        ),
        migrations.AddConstraint(
            model_name='retrogame',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_main_minutes__gte', 1)), name='retro_game_positive_estimate'),
        ),
        migrations.AddConstraint(
            model_name='retrogame',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 1)), name='retro_game_positive_order'),
        ),
        migrations.AddConstraint(
            model_name='retrogame',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['essential', 'complementary'])), name='retro_game_valid_tier'),
        ),
        migrations.AddConstraint(
            model_name='retrogame',
            constraint=models.CheckConstraint(condition=models.Q(('release_year__isnull', True), ('release_year__range', (1970, 2100)), _connector='OR'), name='retro_game_valid_release_year'),
        ),
    ]
