# Generated by Django 5.2.3 on 2026-10-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0020_retrogame_retrogameprogress_retroplatform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64, unique=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('template_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='gameplaytrackingsettings',
            name='reference_source',
            field=models.CharField(choices=[('fixed_daily', 'Diária'), ('routine', 'Rotina')], default='fixed_daily', max_length=16),
        ),
        migrations.CreateModel(
            name='RoutineRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('version', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pomodoro.routineplan')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RoutineBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.UUIDField()),
                ('weekday', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('gameplay', 'Gameplay'), ('cardio', 'Cardio'), ('family', 'Família')], max_length=16)),
                ('profile', models.CharField(choices=[('general', 'Geral'), ('focus', 'Foco'), ('interruptible', 'Interrompível')], max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('end_day_offset', models.PositiveSmallIntegerField(default=0)),
                ('expected_min_minutes', models.PositiveSmallIntegerField(default=None, null=True)),
                ('expected_max_minutes', models.PositiveSmallIntegerField(default=None, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pomodoro.routinerevision')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_date', models.DateField()),
                ('block_id', models.UUIDField()),
                ('source', models.CharField(max_length=8)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pomodoro.group')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='pomodoro.routineplan')),
                ('premium_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pomodoro.premiumperiod')),
                ('return_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pomodoro.group')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.routineplan')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pomodoro.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='pomodoro.routineplan')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRoutinePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('pause_immediately', models.BooleanField(default=None, null=True)),
                ('online', models.BooleanField(default=None, null=True)),
                ('requires_group', models.BooleanField(default=None, null=True)),
                ('competitive', models.BooleanField(default=None, null=True)),
                ('focus_suitable', models.BooleanField(default=None, null=True)),
                ('minimum_minutes', models.PositiveIntegerField(default=None, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.activity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'activity'), name='routine_activity_scope_unique'), models.CheckConstraint(condition=models.Q(('minimum_minutes__isnull', True), models.Q(('minimum_minutes__gte', 1), ('minimum_minutes__lte', 720)), _connector='OR'), name='routine_minimum_valid')],
            },
        ),
        migrations.CreateModel(
            name='RoutineException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_date', models.DateField()),
                ('block_id', models.UUIDField()),
                ('action', models.CharField(max_length=16)),
                ('replacement', models.JSONField(default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='pomodoro.routineplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'origin_date', 'block_id'), name='routine_exception_unique'), models.CheckConstraint(condition=models.Q(('action__in', ['cancel', 'move', 'shorten', 'replace'])), name='routine_exception_action_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='routinerevision',
            constraint=models.UniqueConstraint(fields=('plan', 'effective_from'), name='routine_revision_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineblock',
            constraint=models.UniqueConstraint(fields=('revision', 'block_id'), name='routine_block_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_day_offset__lte', 1), ('weekday__lte', 6)), name='routine_block_valid_days'),
        ),
        migrations.AddConstraint(
            model_name='routineblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_day_offset', 1), ('end_time__gt', models.F('start_time')), _connector='OR'), name='routine_block_positive'),
        ),
        migrations.AddConstraint(
            model_name='routineblock',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['gameplay', 'cardio', 'family']), ('profile__in', ['general', 'focus', 'interruptible']), models.Q(('kind', 'gameplay'), ('profile', 'general'), _connector='OR')), name='routine_block_valid_profile'),
        ),
        migrations.AddConstraint(
            model_name='routineblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expected_max_minutes__isnull', True), ('expected_min_minutes__isnull', True)), models.Q(('expected_max_minutes__isnull', False), ('expected_max_minutes__lte', 1440), ('expected_min_minutes__gte', 1), ('expected_min_minutes__isnull', False), ('expected_min_minutes__lte', models.F('expected_max_minutes')), ('kind', 'cardio')), _connector='OR'), name='routine_cardio_expectation_valid'),
        ),
        migrations.AddConstraint(
            model_name='routineselection',
            constraint=models.UniqueConstraint(fields=('plan', 'origin_date', 'block_id'), name='routine_selection_unique'),
        ),
        migrations.AddConstraint(
            model_name='routineselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('premium_period__isnull', False), ('source', 'premium')), models.Q(('group__isnull', False), ('premium_period__isnull', True), ('source', 'queue')), _connector='OR'), name='routine_selection_source'),
        ),
        migrations.AddConstraint(
            model_name='routinestartrequest',
            constraint=models.UniqueConstraint(fields=('plan', 'request_id'), name='routine_start_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='routinesuspension',
            constraint=models.UniqueConstraint(fields=('plan', 'date'), name='routine_suspension_unique'),
        ),
    ]
