# Generated by Django 5.2.3 on 2026-10-04 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0021_routineplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='routine_requested_occurrence',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='RoutineSessionAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_schedule_id', models.PositiveBigIntegerField(unique=True)),
                ('scope_key', models.CharField(max_length=64)),
                ('block_id', models.UUIDField()),
                ('origin_date', models.DateField()),
                ('revision_version', models.PositiveIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('occurrence_starts_at', models.DateTimeField()),
                ('occurrence_ends_at', models.DateTimeField()),
                ('profile', models.CharField(max_length=16)),
                ('activity_id_snapshot', models.PositiveBigIntegerField()),
                ('activity_name_snapshot', models.CharField(max_length=100)),
                ('execution_origin', models.CharField(choices=[('queue', 'Queue'), ('premium_direct', 'Premium direct'), ('retro_direct', 'Retro direct'), ('legacy', 'Legacy')], max_length=20)),
                ('session_starts_at', models.DateTimeField()),
                ('requested_occurrence', models.JSONField(default=None, null=True)),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_association', to='pomodoro.schedule')),
            ],
            options={
                'indexes': [models.Index(fields=['scope_key', 'origin_date', 'block_id'], name='routine_session_scope_day_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('occurrence_ends_at__gt', models.F('occurrence_starts_at')), ('session_starts_at__gte', models.F('occurrence_starts_at')), ('session_starts_at__lt', models.F('occurrence_ends_at'))), name='routine_session_inside_start')],
            },
        ),
    ]
