# Generated by Django 5.2.3 on 2026-10-09 22:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0022_schedule_routine_requested_occurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScopeLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)])),
                ('runtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('poster_url', models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('watch_url', models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='pomodoro.activity')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_collections', to='pomodoro.category')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)])),
                ('award_edition', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='pomodoro.moviecollection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='pomodoro.movie')),
            ],
            options={
                'ordering': ['award_year', 'movie__release_year', 'movie__activity__name', 'movie_id'],
            },
        ),
        migrations.CreateModel(
            name='MovieDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('dismissed', 'dismissed'), ('invalidated', 'invalidated')], default='pending', max_length=12)),
                ('eligible_count', models.PositiveIntegerField()),
                ('candidate_snapshot', models.JSONField()),
                ('selected_index', models.PositiveIntegerField()),
                ('animation_duration_ms', models.PositiveIntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='pomodoro.moviecollection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='pomodoro.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDrawState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_states', to='pomodoro.moviecollection')),
                ('current_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pomodoro.moviedraw')),
            ],
        ),
        migrations.CreateModel(
            name='MovieMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'request_id'), name='movie_mutation_request_unique')],
            },
        ),
        migrations.CreateModel(
            name='MovieProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('unwatched', 'unwatched'), ('watching', 'watching'), ('watched', 'watched')], default='unwatched', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='pomodoro.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('previous_status', models.CharField(max_length=12)),
                ('next_status', models.CharField(max_length=12)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pomodoro.moviedraw')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_events', to='pomodoro.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('release_year__gte', 1888), ('release_year__lte', 2100)), name='movie_release_year_range'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('runtime_minutes__isnull', True), models.Q(('runtime_minutes__gte', 1), ('runtime_minutes__lte', 1440)), _connector='OR'), name='movie_runtime_range'),
        ),
        migrations.AddIndex(
            model_name='moviecollectionentry',
            index=models.Index(fields=['collection', 'award_year'], name='movie_entry_award_idx'),
        ),
        migrations.AddConstraint(
            model_name='moviecollectionentry',
            constraint=models.UniqueConstraint(fields=('collection', 'movie'), name='movie_entry_collection_unique'),
        ),
        migrations.AddConstraint(
            model_name='moviecollectionentry',
            constraint=models.CheckConstraint(condition=models.Q(('award_year__gte', 1888), ('award_year__lte', 2100)), name='movie_award_year_range'),
        ),
        migrations.AddConstraint(
            model_name='moviecollectionentry',
            constraint=models.CheckConstraint(condition=models.Q(('award_edition__isnull', True), ('award_edition__gte', 1), _connector='OR'), name='movie_award_edition_positive'),
        ),
        migrations.AddIndex(
            model_name='moviedraw',
            index=models.Index(fields=['scope_key', 'collection', '-selected_at'], name='movie_draw_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='moviedraw',
            constraint=models.UniqueConstraint(fields=('scope_key', 'request_id'), name='movie_draw_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='moviedraw',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('scope_key', 'collection'), name='movie_draw_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='moviedraw',
            constraint=models.CheckConstraint(condition=models.Q(('animation_duration_ms__gte', 5000), ('animation_duration_ms__lte', 10000)), name='movie_draw_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='moviedraw',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_count__gte', 1), ('selected_index__lt', models.F('eligible_count'))), name='movie_draw_index_range'),
        ),
        migrations.AddConstraint(
            model_name='moviedraw',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'pending')), models.Q(('resolved_at__isnull', False), ('status__in', ['accepted', 'dismissed', 'invalidated'])), _connector='OR'), name='movie_draw_status_dates'),
        ),
        migrations.AddConstraint(
            model_name='moviedrawstate',
            constraint=models.UniqueConstraint(fields=('scope_key', 'collection'), name='movie_draw_state_scope_unique'),
        ),
        migrations.AddIndex(
            model_name='movieprogress',
            index=models.Index(fields=['scope_key', 'status'], name='movie_progress_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='movieprogress',
            constraint=models.UniqueConstraint(fields=('scope_key', 'movie'), name='movie_progress_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='movieprogress',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='movie_progress_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='movieprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', True), ('status', 'unwatched'), ('watched_at__isnull', True)), models.Q(('started_at__isnull', False), ('status', 'watching'), ('watched_at__isnull', True)), models.Q(('status', 'watched'), ('watched_at__isnull', False)), _connector='OR'), name='movie_progress_status_dates'),
        ),
        migrations.AddIndex(
            model_name='movieprogressevent',
            index=models.Index(fields=['scope_key', '-occurred_at', '-id'], name='movie_event_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='movieprogressevent',
            constraint=models.UniqueConstraint(fields=('scope_key', 'request_id'), name='movie_event_request_unique'),
        ),
    ]
