# Generated by Django 5.2.3 on 2026-10-09 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0023_moviescopelock_movie_moviecollection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('csv_text', models.TextField()),
                ('status', models.CharField(choices=[('queued_preview', 'Aguardando prévia'), ('previewing', 'Preparando prévia'), ('ready', 'Prévia pronta — confirme para importar'), ('queued_import', 'Aguardando importação'), ('importing', 'Importando'), ('done', 'Importação concluída'), ('failed', 'Falha — nenhuma alteração deste processamento foi aplicada')], db_index=True, default='queued_preview', max_length=20)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
