# Generated by Django 5.2.3 on 2026-10-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0024_movieimportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('tier', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pomodoro.moviecollection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pomodoro.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'collection', 'movie'), name='movie_tier_rating_scope_unique'), models.CheckConstraint(condition=models.Q(('tier__in', ['S', 'A', 'B', 'C', 'D'])), name='movie_tier_value_valid')],
            },
        ),
        migrations.CreateModel(
            name='MovieTierState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pomodoro.moviecollection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'collection'), name='movie_tier_state_scope_unique')],
            },
        ),
    ]
